name: DMPEnderCrystal
main: email.com.gmail.cosmoconsole.bukkit.dmp.endercrystal.Main
version: 1.2.1
api-version: 1.13
description: Allows Ender Crystal kills to be tracked with DMP with natural.EnderCrystalKill.
author: CosmoConsole
depend: [DeathMessagesPrime]
